import { createAction } from 'redux-actions';

export default {
    'RECIPES/RECIPES_ADDED_SUCCESSFULLY': createAction("RECIPES/RECIPES_ADDED_SUCCESSFULLY"),
    'RECIPES/SET_RECIPES': createAction('RECIPES/SET_RECIPES'),
    "RECIPES/LOAD_DATA": createAction("RECIPES/LOAD_DATA"),
    'RECIPES/RECIPE_REMOVE': createAction('RECIPES/RECIPE_REMOVE'),
    'RECIPES/RECIPES_REMOVE_ALL': createAction('RECIPES/RECIPES_REMOVE_ALL'),
    'RECIPES/RECIPE_EDIT': createAction('RECIPES/RECIPE_EDIT')
}